Support for specific node versions
adobe/aio-cli pull request #220
Opened 2020-10-12 13:41 UTC by Himavanth

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-10-12 16:20 UTC, Himavanth commented
We can do this for all our plugins listed under https://github.com/adobe/aio-cli#aio-cli-health . Should we also do this for our libraries or would that be an overkill ? WDYT @meryllblanchet @shazron

2020-10-15 03:12 UTC, shazron approved these changes

2020-10-29 17:33 UTC, meryllblanchet commented
Sorry @Himavanth I missed your last question. It is fine for me to make this only for each plugin that we do support.
The SDK libraries are either used by CLI plugins (which check the version with changes similar to this PR), or by Runtime actions, for which we control what container kinds can be used.

2021-05-25 13:09 UTC, shazron requested changes
Needs to be updated to support 12 and 14 only

2021-05-27 02:38 UTC, shazron approved these changes

2021-05-27 02:39 UTC, merged